version: '3.9'

services:
  app:
    container_name: fullstack-next-prod
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      - NODE_ENV=development
      - CODECOV_TOKEN=${CODECOV_TOKEN}
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
